spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_sec
spring.datasource.username=root
spring.datasource.password=Quanfey

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=amrapari

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alamparvej2024@gmail.com
spring.mail.password=cymjnvdavdflhcjx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT ? fixed secret so tokens survive server restarts
# Generate your own: openssl rand -base64 32
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VuIGdlbmVyYXRpb24h
jwt.access-token-expiry=600000
jwt.refresh-token-expiry=604800000

## To save image data (recommended, standard web convention)
# sudo mkdir -p /var/www/parvej-backend/uploads/slides
# sudo chown -R $USER:$USER /var/www/parvej-backend/uploads
#s udo chmod -R 755 /var/www/parvej-backend/uploads
file.upload-dir=/var/www/parvej-backend/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB