INSERT INTO class_info (id,class_name, description, instructor, schedule, capacity, enrolled, active, created_at) VALUES
(1,'Mathematics 101', 'Introduction to basic mathematics covering algebra, geometry, and trigonometry. Perfect for beginners.', 'Dr. Sarah Johnson', 'Monday, Wednesday, Friday 9:00 AM - 10:30 AM', 30, 25, true, CURRENT_TIMESTAMP),
(2,'Computer Science Fundamentals', 'Learn the basics of programming, data structures, and algorithms. No prior experience required.', 'Prof. Michael Chen', 'Tuesday, Thursday 2:00 PM - 4:00 PM', 25, 20, true, CURRENT_TIMESTAMP),
(3,'English Literature', 'Explore classic and modern literature from around the world. Develop critical reading and writing skills.', 'Dr. Emily Williams', 'Monday, Wednesday 11:00 AM - 12:30 PM', 35, 30, true, CURRENT_TIMESTAMP),
(4,'Physics for Engineers', 'Advanced physics concepts including mechanics, thermodynamics, and electromagnetism.', 'Prof. David Martinez', 'Tuesday, Thursday 10:00 AM - 12:00 PM', 20, 18, true, CURRENT_TIMESTAMP),
(5,'History of Art', 'Journey through art history from ancient civilizations to contemporary art movements.', 'Dr. Lisa Anderson', 'Friday 1:00 PM - 4:00 PM', 40, 35, true, CURRENT_TIMESTAMP);

insert into home_slides values
(1, true, now(), 'Experience structured courses with interactive lessons, quizzes, and hands-on projects designed to make learning practical and engaging.', 35, 'https://plus.unsplash.com/premium_photo-1673292293042-cafd9c8a3ab3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'https://www.quantummethod.org', 'Interactive Learning Experience', now()),
(2, true, now(), 'Track your learning progress with smart dashboards, performance analytics, and personalized recommendations.', 35, 'https://plus.unsplash.com/premium_photo-1673292293042-cafd9c8a3ab3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'https://www.quantummethod.org', 'Smart Progress Tracking', now()),
(3, true, now(), 'Learn from experienced instructors and industry professionals who guide you through real-world skills and concepts.', 35, 'https://plus.unsplash.com/premium_photo-1673292293042-cafd9c8a3ab3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'https://www.quantummethod.org', 'Learn from Expert Instructors', now()),
(4, true, now(), 'Build your career with practical courses, certifications, and skill-based learning paths tailored for modern education.', 35, 'https://plus.unsplash.com/premium_photo-1673292293042-cafd9c8a3ab3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'https://www.quantummethod.org', 'Career-Focused Learning', now()),
(5, true, now(), 'Access your courses anytime from any device and continue learning at your own pace without limitations.', 35, 'https://plus.unsplash.com/premium_photo-1673292293042-cafd9c8a3ab3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'https://www.quantummethod.org', 'Flexible Learning for Everyone', now());


INSERT INTO users (id, email, password, reset_token, reset_token_expiry, role, username) VALUES
(13,'alamparvej2024@gmail.com','$2a$12$oPE5DRJeQ72/tBNlHp/uRusuoSVOj.m05HnvaofqohyDJDtxoNeEO',NULL,NULL,'SYSTEM','system');